server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761

spring:
  cloud:
    discovery:
      enabled: true

  application:
    name: eureka-server
