server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761
    register-with-eureka: false
    fetch-registry: false

spring:
  cloud:
    discovery:
      enabled: true

  application:
    name: eureka-server
