spring:
  main:
    allow-circular-references: true
#  security:
#    user:
#      name: user
#      password: user
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/app1?createDatabaseIfNotExist=true
    username:  root
    password:  root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  application:
    name: invoice-server

server:
  port: 8089
  servlet:
    context-path: /api-invoice

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



resilience4j:
  retry:
    instances:
      getAllClient:
        max-attempts: 5
        wait-duration: 2s
        retry-exceptions: org.springframework.web.client.ResourceAccessException

  rate-limiter:
    instances:
      allTest:
        limit-for-period: 2
        limit-refresh-period: 5s
        timeout-duration: 0



